Better reporting of errors when JAXP not present.
Catch NoClassDefFoundError as well as NullPointerException and
emit a more meaningful error message.

Change BuildException to accept Errors as well as Exceptions
as cause.

Submitted by:	Stefan Bodewig <bodewig@bost.de>


git-svn-id: https://svn.apache.org/repos/asf/ant/core/trunk@267682 13f79535-47bb-0310-9956-ffa450edef68