Fix `--release` param check in bootstrap.bat
The following check will always fail silently due to batch `echo` always
taking strings literally - including double quotes:

    echo "public class JavacVersionCheck {}" >%CLASSDIR%\JavacVersionCheck.java
    "%JAVAC%" --release 8 -d %CLASSDIR% %CLASSDIR%\JavacVersionCheck.java >nul 2>&1

With the following error message:

    JavacVersionCheck.java:1: error: class, interface, or enum expected
    "public class JavacVersionCheck {}"
    ^
    1 error

Even with that fixed, the next statement will crash and burn on systems
that do not have Command Extensions enabled (e.g. invoked with `cmd /y`):

    IF %ERRORLEVEL% EQU 0 SET JAVAC_RELEASE_VERSION="--release 8"

With the following error message:

    EQU was unexpected at this time.

In order to accommodate that, those checks have been corrected.

Signed-off-by: Mateusz Kazimierczuk <mataha@shimiko.download>